name: Test and Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
        
    - name: Install dependencies
      run: bun install
      
    - name: Run TypeScript check
      run: bun run tsc --noEmit
      
    - name: Run tests
      run: bun test
      
    - name: Build binary
      run: bun run build
      
    - name: Test binary
      run: |
        ./dist/catd --version
        ./dist/catd --help
        
    - name: Upload binary artifact
      uses: actions/upload-artifact@v4
      with:
        name: catd-linux
        path: dist/catd

  build-macos:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
        
    - name: Install dependencies
      run: bun install
      
    - name: Build binary
      run: bun run build
      
    - name: Test binary
      run: |
        ./dist/catd --version
        ./dist/catd --help
        
    - name: Upload binary artifact
      uses: actions/upload-artifact@v4
      with:
        name: catd-macos
        path: dist/catd 